server:
  port: ${CUSTOM_SERVER_PORT:9090}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    
spring:
  cloud:
      gateway:
        routes:
          - id: user-service
            uri:  user-service:9004
            predicates:
              - Path=/api/user-service/**
            filers:
              - StripPrefix=2
 