server:
  port: ${CUSTOM_SERVER_PORT:9002}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: biaster
      uri: mongodb://localhost:27017/
      authentication-database: admin
